# Generated by Django 4.2.5 on 2023-10-09 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_users', '0002_alter_installationpersons_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationpersons',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectmanagers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salespersons',
            name='name',
        ),
        migrations.CreateModel(
            name='SuperuserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
