# Generated by Django 4.2.5 on 2023-10-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0004_projectmanagers_fcm_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanagers',
            old_name='fcm_id',
            new_name='push_token',
        ),
        migrations.AddField(
            model_name='installationpersons',
            name='push_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespersons',
            name='push_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superuserrequest',
            name='push_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
