# Generated by Django 4.2.5 on 2023-10-18 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0005_rename_fcm_id_projectmanagers_push_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationpersons',
            name='logged_in',
            field=models.CharField(default='installation_person', max_length=50),
        ),
        migrations.AddField(
            model_name='projectmanagers',
            name='logged_in',
            field=models.CharField(default='project_manager', max_length=50),
        ),
        migrations.AddField(
            model_name='salespersons',
            name='logged_in',
            field=models.CharField(default='sales_person', max_length=50),
        ),
        migrations.AlterField(
            model_name='superuserrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
